name: Close Jira issue
on:
  issues:
    types:
      - closed

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find in Jira ticket
        uses: atlassian/gajira-find-issue-key@master
        id: jira-ticket
        with:
          from: commits

      - name: Transition issue
        if: steps.jira-ticket.outputs.issue != ''
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.jira-ticket.outputs.issue }}
          transition: "완료"