name: Opend PR Notification
on:
  pull_request:
    branches:
      - develop
      - release
      - main
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: add google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Send Success Message
        if: ${{ success() }}
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: BFF WONDER FORVER SHADOW JENNY BOT
          DISCORD_AVATAR: https://cdn-icons-png.flaticon.com/128/8290/8290674.png
          DISCORD_EMBEDS: |
            [
              { 
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "title": "PR 성공, 리뷰 자~ 두 과 자 ~! 🥳🥳\n#${{ github.event.pull_request.number }} : ${{ github.event.pull_request.title }}",
                "color": 10478271,
                "description": "${{ github.event.pull_request.html_url }}",
                "fields": [
                  {
                    "name": "Base Branch",
                    "value": "${{ github.base_ref }}",
                    "inline": true
                  },
                  {
                    "name": "Compare Branch",
                    "value": "${{ github.head_ref }}",
                    "inline": true
                  }
                ]
              }
            ]
            
      - name: Send Failure Message
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: BFF WONDER FORVER SHADOW JENNY BOT
          DISCORD_AVATAR: https://cdn-icons-png.flaticon.com/128/8290/8290674.png
          DISCORD_EMBEDS: |
            [
              { 
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "https://github.com/pknu-wap/WAPP/blob/main/image/icon.png?raw=true",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "title": "PR 실패, 이 친구 내 성격 까먹었나보네,, 👊👊 \n#${{ github.event.pull_request.number }} : ${{ github.event.pull_request.title }}",
                "color": 13458524,
                "description": "${{ github.event.pull_request.html_url }}",
                "fields": [
                  {
                    "name": "Base Branch",
                    "value": "${{ github.base_ref }}",
                    "inline": true
                  },
                  {
                    "name": "Compare Branch",
                    "value": "${{ github.head_ref }}",
                    "inline": true
                  }
                ]
              }
            ]
